---
title: "Slides"
---

See below for slides and other material from conference talks that I've given


[August 2017](https://statsbylopez.github.io/JSM2017_files/JSM2017.html) Slides for the 2017 Joint Statistical Meetings on developing a model to assess parity in professional sports, particularly with respect to the National Football League

[April, 2017](https://dl.dropboxusercontent.com/u/42748635/All%20sport%20talk/Slides.FtoFtalk.html#1) Slides from a faculty-to-faculty talk at Skidmore College: "How statistics can be used to help us better understand sports"

[August, 2016](statsbylopez.github.io/Slides/jsm16/Slides.JSM.html#1) Slides from the 2016 Joint Statistical Meetings: "Ref's -- they're just like us!  Adversarial and social pressures in the NFL"

[October, 2016](https://github.com/statsbylopez/Boston-Hockey-Analytics-16/blob/master/BOSHAC.pdf) Slides and code from a workshop on reproducible hockey analysis at the Boston Hockey Analytics Conference

[April, 2016](statsbylopez.github.io/Slides/talk_NESS_2016.ppt) Slides from the 2016 New England Statistics Symposium: "Causal inference in healthcare studies with multiple treatments"

[March, 2016](https://statsbylopez.files.wordpress.com/2016/03/columbia_ml_2016.pdf) Slides from a guest lecture at Columbia: "Better than lotto tickets: Analytics and NCAA tournament win probabilities"

[October 2015](https://github.com/statsbylopez/ICHPS) Code and material from my workshop on causal inference with multiple treatments from the 2015 International Conference on Health Policy Statistics 

[September, 2015](https://dl.dropboxusercontent.com/u/42748635/NESSIS.hockey/Slides.NESSIS.html#1) Slides on the NHL's shootout from the 2015 New England Symposium on Sports and Statistics: "Predicting coin flips"

[August 2014](https://statsbylopez.files.wordpress.com/2014/08/jsm2014_nhl.pdf) Slides for the 2014 Joint Statistical Meetings: "The NHL needs a new point system and it needed a new one a decade ago""


